server:
  port: 8080
spring:
  application:
    name: dubbo-provider

dubbo:
  application:
    name: dubbo-provider #当前服务/应用的名字
  registry:
    address: 192.168.11.128:2181  #注册中心地址
    protocol: zookeeper  #注册中心协议
  protocol:
    name: dubbo  #通信规则（通信协议和接口）
    port: 20881  #通信规则（通信协议和接口）
  scan:
    base-packages: com.cg.demo.service