server:
  port: 8081
  servlet:
    context-path: /consumer
spring:
  application:
    name: service-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能